name: Apply repo settings

on:
  push:
    branches:
      - main
    paths:
      - ".github/settings.yml"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh repo edit --enable-issues=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
