name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: just static

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: just test
