name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  devcontainer:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: echo "Devcontainer built"

  static:
    name: Run Static Analysis
    needs: devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: just static

  test:
    name: Run Tests
    needs: devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: just test

  done:
    name: 🥳
    needs: [test, static]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
